language: python
jobs:
    include:
        - python: "3.8-dev"
        - python: "3.8"
        - python: "3.7"
        - python: "3.6"
install:
    - pip install -r requirements-test.txt
script:
    - make test
    - make lint
    - make format && git diff --quiet HEAD
